<?php

return [
    'permissions' => [
        ['name' => 'dashboard.view', 'description' => 'View dashboard'],
        ['name' => 'users.view', 'description' => 'View users'],
        ['name' => 'users.create', 'description' => 'Create users'],
        ['name' => 'users.edit', 'description' => 'Edit users'],
        ['name' => 'users.delete', 'description' => 'Delete users'],
        ['name' => 'users.suspend', 'description' => 'Suspend users'],
        ['name' => 'orders.view', 'description' => 'View orders'],
        ['name' => 'orders.create', 'description' => 'Create orders'],
        ['name' => 'orders.edit', 'description' => 'Edit orders'],
        ['name' => 'orders.cancel', 'description' => 'Cancel orders'],
        ['name' => 'payments.view', 'description' => 'View payments'],
        ['name' => 'payments.refund', 'description' => 'Refund payments'],
        ['name' => 'subscriptions.view', 'description' => 'View subscriptions'],
        ['name' => 'subscriptions.create', 'description' => 'Create subscriptions'],
        ['name' => 'subscriptions.edit', 'description' => 'Edit subscriptions'],
        ['name' => 'subscriptions.suspend', 'description' => 'Suspend subscriptions'],
        ['name' => 'subscriptions.renew', 'description' => 'Renew subscriptions'],
        ['name' => 'subscriptions.revoke', 'description' => 'Revoke subscriptions'],
        ['name' => 'plans.view', 'description' => 'View VPN plans'],
        ['name' => 'plans.create', 'description' => 'Create VPN plans'],
        ['name' => 'plans.edit', 'description' => 'Edit VPN plans'],
        ['name' => 'plans.delete', 'description' => 'Delete VPN plans'],
        ['name' => 'nodes.view', 'description' => 'View VPN nodes'],
        ['name' => 'nodes.create', 'description' => 'Create VPN nodes'],
        ['name' => 'nodes.edit', 'description' => 'Edit VPN nodes'],
        ['name' => 'nodes.delete', 'description' => 'Delete VPN nodes'],
        ['name' => 'nodes.health', 'description' => 'View node health'],
        ['name' => 'staff.view', 'description' => 'View staff'],
        ['name' => 'staff.manage', 'description' => 'Manage staff'],
        ['name' => 'roles.manage', 'description' => 'Manage roles'],
        ['name' => 'permissions.manage', 'description' => 'Manage permissions'],
        ['name' => 'coupons.view', 'description' => 'View coupons'],
        ['name' => 'coupons.manage', 'description' => 'Manage coupons'],
        ['name' => 'affiliate.view', 'description' => 'View affiliate'],
        ['name' => 'affiliate.manage', 'description' => 'Manage affiliate'],
        ['name' => 'support.view', 'description' => 'View support'],
        ['name' => 'support.manage', 'description' => 'Manage support'],
        ['name' => 'settings.view', 'description' => 'View settings'],
        ['name' => 'settings.manage', 'description' => 'Manage settings'],
        ['name' => 'audit_logs.view', 'description' => 'View audit logs'],
    ],
    'customer_permissions' => [
        'dashboard.view',
        'orders.view',
        'subscriptions.view',
        'subscriptions.renew',
        'plans.view',
        'support.view',
        'support.manage',
    ],
];